from edxml.ontology import OntologyElement


def assert_valid_upgrade(old: OntologyElement, new: OntologyElement): ...

def assert_incomparable(old: OntologyElement, new: OntologyElement): ...

def assert_valid_ontology_upgrade(old: OntologyElement, new: OntologyElement): ...

def assert_invalid_ontology_upgrade(old: OntologyElement, new: OntologyElement): ...
